name: Proxy List

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Update proxies
      run: python update_proxies.py

    - name: Commit changes
      run: |
        git config --global user.name "Ritu Raj Pratap Singh"
        git config --global user.email "theriturajps@gmail.com"
        git add .
        git commit -m "Updated ➠ $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
        git push