name: Proxy List Updater

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:     # Allows manual triggering
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Update proxies
      run: python proxies.py

    - name: Build website
      run: |
        mkdir -p docs
        cp proxies.json docs/
        cp index.html docs/
        cp style.css docs/

    - name: Commit changes
      run: |
        git config --global user.name "Ritu Raj Pratap Singh"
        git config --global user.email "theriturajps@gmail.com"
        git add .
        git commit -m "Auto-update proxies and website ➠ $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
        git push