
3. Updated `update.yml` workflow:

```yaml
name: Advanced Proxy List Updater

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:     # Allows manual triggering
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Update proxies
      run: python proxies.py

    - name: Commit changes
      run: |
        git config --global user.name "Proxy List Updater"
        git config --global user.email "proxy-updater@users.noreply.github.com"
        git add .
        git commit -m "Updated ➠ $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
        git push